# Post render script configuration
# if this is false then github steps won't happen either
MAKE_WEBSITE_DIR: true
DO_GITHUB: true

# name of directory to create for website
WEBSITE_DIR: docs


# name of directory where quarto rendered the website
OUTPUT_DIR: site_tmp

# remove the output directory after the website is created?
REMOVE_OUTPUT_DIR: true

# github path for the rendered website. Something like git@github.com:GithubUserName/RepositoryName.git
ORIGIN: git@github.com:KBurbank/stat24320.git